//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormDetail
    {
        public int SupplierID { get; set; }
        public int BookID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> NumberOfBooks { get; set; }
        public Nullable<System.DateTime> DateOfImport { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
